version: '3.9'

services:
  mysql_microservices:
    image: mysql:8.0-debian
    container_name: mysql_microservices
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: microservices
    volumes:
      - data-mysql-orders:/var/lib/mysql
    restart: always
    networks:
      - microservices_network

  zipkin:
    image: openzipkin/zipkin
    container_name: zipkin
    ports:
      - "9411:9411"
    restart: always
    networks:
      - microservices_network

  redis:
    image: redis
    container_name: redis
    ports:
      - "6379:6379"
    restart: always
    networks:
      - microservices_network


volumes:
  data-mysql-orders:

networks:
  microservices_network:
    driver: bridge